"""add provider and model columns to chats

Revision ID: 8b6b1a10edc1
Revises: 6ec3948e4a59
Create Date: 2026-07-02 16:59:56.151103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6b1a10edc1'
down_revision: Union[str, Sequence[str], None] = '6ec3948e4a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('provider', sa.String(), nullable=False, server_default='ollama'))
    op.add_column('chats', sa.Column('model', sa.String(), nullable=False, server_default='qwen2.5:3b'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'model')
    op.drop_column('chats', 'provider')
    # ### end Alembic commands ###
